dependencies:
  - pip=23.3.1
  - python=3.11
  - pip:
      - numpy==1.26.3
      - matplotlib==3.8.3
      - git+https://github.com/VSPEC-collab/VSPEC.git@release/1.0.0
      - git+https://github.com/VSPEC-collab/vspec-vsm.git@main
      - git+https://github.com/VSPEC-collab/GridPolator.git@release/0.4.2
      - git+https://github.com/tedjohnson12/libpypsg.git@main
      - cartopy==0.22.0
      - pandas==2.2.0
    
run:
  - python3 src/scripts/setup_psg.py
