name: build pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Fix dependencies
        env:
          PSG_API_KEY: ${{ secrets.PSG_API_KEY }}
        run: |
          conda install -y pip
          pip install pulp==2.7.0
          python3 -c "import pypsg; pypsg.settings.save_settings(api_key='${{ env.PSG_API_KEY }}')"

      - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v1
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
